INSERT INTO `mallbuilder_district` VALUES ('45052', 'China/ÖÐ¹ú', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45053', 'Algeria', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45054', 'American Samoa', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45055', 'Andorra', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45056', 'Angola', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45057', 'Anguilla', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45058', 'Antigua and Barbuda', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45059', 'Argentina', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45060', 'Armenia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45061', 'Aruba', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45062', 'Australia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45063', 'Austria', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45064', 'Azerbaijan', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45065', 'Bahamas', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45066', 'Bahrain', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45067', 'Bangladesh', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45068', 'Barbados', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45069', 'Belarus', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45070', 'Belgium', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45071', 'Belize', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45072', 'Bermuda', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45073', 'Bhutan', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45074', 'Bolivia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45075', 'Bosnia and Herzegovina', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45076', 'Botswana', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45077', 'Bouvet Island', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45078', 'Brazil', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45079', 'Brunei Darussalam', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45080', 'Bulgaria', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45081', 'Burkina Faso', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45082', 'Burundi', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45083', 'Cameroon', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45084', 'Canada', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45085', 'Cape Verde', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45086', 'Cayman Islands', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45087', 'Central African Republic', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45088', 'Chad', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45089', 'Chile', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45090', 'Christmas Island', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45091', 'Cocos (Keeling) Islands', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45092', 'Colombia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45093', 'Comoros', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45094', 'Congo, Republic of the', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45095', 'Cook Islands', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45096', 'Costa Rica', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45097', 'Croatia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45098', 'Cuba', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45099', 'Cyprus', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45100', 'Czech Republic', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45101', 'Denmark', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45102', 'Djibouti', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45103', 'Dominica, Commonwealth of the', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45104', 'Dominican Republic', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45105', 'Ecuador', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45106', 'Egypt', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45107', 'El Salvador', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45108', 'Equatorial Guinea', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45109', 'Eritrea', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45110', 'Estonia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45111', 'Ethiopia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45112', 'Islas Malvinas (Falkland Islands)', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45113', 'Fiji', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45114', 'Finland', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45115', 'France', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45116', 'French Guiana', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45117', 'Gabon', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45118', 'Gambia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45119', 'Georgia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45120', 'Germany', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45121', 'Ghana', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45122', 'Gibraltar', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45123', 'Greece', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45124', 'Greenland', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45125', 'Grenada', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45126', 'Guadeloupe', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45127', 'Guam', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45128', 'Guatemala', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45129', 'Guinea-Bissau', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45130', 'Guinea', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45131', 'Guyana', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45132', 'Haiti', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45133', 'Honduras', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45134', 'Hungary', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45135', 'Iceland', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45136', 'India', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45137', 'Indonesia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45138', 'Iran', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45139', 'Iraq', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45140', 'Ireland', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45141', 'Israel', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45142', 'Italy', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45143', 'Jamaica', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45144', 'Japan', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45145', 'Jordan', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45146', 'Kazakhstan', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45147', 'Kenya', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45148', 'Kiribati', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45149', 'Kuwait', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45150', 'Kyrgyzstan', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45151', 'Laos', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45152', 'Latvia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45153', 'Lebanon', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45154', 'Lesotho', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45155', 'Liberia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45156', 'Libya', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45157', 'Liechtenstein', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45158', 'Lithuania', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45159', 'Luxembourg', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45160', 'Madagascar', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45161', 'Malawi', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45162', 'Malaysia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45163', 'Maldives', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45164', 'Mali', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45165', 'Malta', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45166', 'Marshall Islands', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45167', 'Mauritania', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45168', 'Mauritius', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45169', 'Mexico', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45170', 'Moldova', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45171', 'Monaco', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45172', 'Mongolia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45173', 'Montserrat', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45174', 'Morocco', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45175', 'Mozambique', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45176', 'Namibia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45177', 'Nauru', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45178', 'Nepal', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45179', 'Netherlands', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45180', 'New Caledonia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45181', 'New Zealand', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45182', 'Nicaragua', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45183', 'Niger', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45184', 'Nigeria', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45185', 'Niue', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45186', 'Norfolk Island', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45187', 'D.P.R.Korea', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45188', 'Norway', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45189', 'Oman', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45190', 'Pakistan', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45191', 'Palau', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45192', 'Panama', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45193', 'Papua New Guinea', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45194', 'Paraguay', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45195', 'Peru', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45196', 'Philippines', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45197', 'Pitcairn Island', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45198', 'Poland', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45199', 'Portugal', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45200', 'Puerto Rico', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45201', 'Qatar', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45202', 'Romania', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45203', 'Russia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45204', 'Rwanda', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45205', 'Samoa', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45206', 'San Marino', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45207', 'Sao Tome and Principe', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45208', 'Saudi Arabia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45209', 'Senegal', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45210', 'Seychelles', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45211', 'Sierra Leone', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45212', 'Singapore', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45213', 'Slovakia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45214', 'Slovenia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45215', 'Solomon Islands', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45216', 'Somalia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45217', 'South Africa', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45218', 'R.O.Korea', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45219', 'Spain', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45220', 'Sri Lanka', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45221', 'Saint Helena', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45222', 'Saint Kitts and Nevis', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45223', 'Saint Lucia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45224', 'Saint Pierre and Miquelon', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45225', 'Saint Vincent and the Grenadines', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45226', 'Sudan', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45227', 'Suriname', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45228', 'Svalbard', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45229', 'Swaziland', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45230', 'Sweden', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45231', 'Switzerland', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45232', 'Syria', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45233', 'Tajikistan', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45234', 'Tanzania', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45235', 'Thailand', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45236', 'Togo', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45237', 'Tokelau', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45238', 'Tonga', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45239', 'Trinidad and Tobago', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45240', 'Tunisia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45241', 'Turkey', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45242', 'Turkmenistan', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45243', 'Turks and Caicos Islands', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45244', 'Tuvalu', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45245', 'Uganda', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45246', 'Ukraine', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45247', 'United Kingdom', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45248', 'United States', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45249', 'United States Pacific Island Wildlife Refuges', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45250', 'Uruguay', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45251', 'Uzbekistan', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45252', 'Venezuela', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45253', 'Vietnam', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45254', 'British Virgin Islands', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45255', 'United States Virgin Islands', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45256', 'Yemen', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45257', 'Congo, Democratic Republic of the', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45258', 'Zambia', '0', '0');
INSERT INTO `mallbuilder_district` VALUES ('45259', 'Zimbabwe', '0', '0');

UPDATE `mallbuilder_district` SET `pid` = '45052' WHERE `id` < 35 ;
DELETE FROM `mallbuilder_district` WHERE `id` = 35 ;
DELETE FROM `mallbuilder_district` WHERE `pid` = 35 ;
