<?php
include("includes/global.php");
//====================================
$sql="  delete from hy_admin_operation_log;
		delete from hy_album;
		delete from hy_auditing;
		delete from hy_blog;
		delete from hy_brand;
		delete from hy_brand_cat;
		delete from hy_business_info;
		delete from hy_comment;
		delete from hy_contags;
		delete from hy_custom_cat;
		delete from hy_fast_mail;
		delete from hy_fav_cat;
		delete from hy_fav_list;
		delete from hy_feed;
		delete from hy_filter_keyword;
		delete from hy_friend;
		delete from hy_logistics_addr;
		delete from hy_logistics_temp;
		delete from hy_logistics_temp_con;
		delete from hy_mail_record;
		delete from hy_message;
		delete from hy_module;
		delete from hy_news;
		delete from hy_news_data;
		delete from hy_newscat;
		delete from hy_notice;
		delete from hy_page_rec;
		delete from hy_page_view;
		delete from hy_payment_banks;
		delete from hy_payment_card;
		delete from hy_payment_cashflow;
		delete from hy_payment_cashpickup;
		delete from hy_payment_type;
		delete from hy_payment_user;
		delete from hy_product_cart;
		delete from hy_product_cat;
		delete from hy_product_comment;
		delete from hy_product_delivery;
		delete from hy_product_detail;
		delete from hy_product_invoice;
		delete from hy_product_order;
		delete from hy_product_order_pro;
		delete from hy_product_report;
		delete from hy_product_report_subject;
		delete from hy_product_setmeal;
		delete from hy_products;
		delete from hy_reg_vercode;
		delete from hy_reserve_username;
		delete from hy_search_word;
		delete from hy_shareproduct;
		delete from hy_shareproduct_info;
		delete from hy_shareshop;
		delete from hy_shop_navigation;
		delete from hy_shop_setting;
		delete from hy_site_spread;
		delete from hy_special;
		delete from hy_special_layout;
		delete from hy_stop_ip;
		delete from hy_sub_domain;
		delete from hy_subscribe;
		delete from hy_tags;
		delete from hy_tg;
		delete from hy_tg_cat;
		delete from hy_tg_order;
		delete from hy_user;
		delete from hy_user_all;
		delete from hy_user_cat;
		delete from hy_user_comment;
		delete from hy_user_connected;
		delete from hy_user_detail;
		delete from hy_user_domin;
		delete from hy_user_earnest;
		delete from hy_user_group;
		delete from hy_user_link;
		delete from hy_user_orderadder;
		delete from hy_user_read_rec;
		delete from hy_user_template;
		delete from hy_vote;
		delete from hy_web_con;
		delete from hy_web_con_group;
		delete from hy_web_config;
		delete from hy_web_extend_cat;
		delete from hy_web_extend_file;
		delete from hy_web_link;
";
$sql_con=explode(";",$sql);
foreach($sql_con as $v)
{
	$str=str_replace('hy_',$config['table_pre'],$v);
	$db->query($str);
}
echo 'clear ok';
?>